# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..5

sass:
  style: compressed

# Site Data
  url: https://dwykat.github.io
baseurl:
title: Mission
description: Where there is a will, there is a way.
keywords: 'jekyll,python,code,blog,algorithm'
author:
  name: Learner
  job_title:
  location:
  email: brucecser@foxmail.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/dwykat
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url:
    - name: vk
      url:
home:
  section1: <h1>Mission</h1>
  section2: <h2>Where there is a will, there is a way.</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/dwykat/dwykat.github.io" title="View on GitHub"></a></div>
blog:
  cc_license:  http://creativecommons.org/licenses/by-sa/4.0/
  cc_license_image: /assets/images/theme/cc-by-sa.png
  footer_content: Where there is a will, there is a way.

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id:

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
