# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true 
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..5

sass:
  style: compressed

# Site Data
  url: "https://todebug.com" 
# the base hostname & protocol for your site, e.g. http://example.com
baseurl: 
title: V
description: "For man is man and master of his fate."
keywords: 'jekyll,python,code,blog,algorithm'
author:
  name: Aaron
  job_title:
  location:
  email: isyangkai@gmail.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/bryceyang
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>V</h1>
  section2: <h2>For man is man and master of his fate.</h2>
 #section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/bryceyang/bryceyang.github.io" title="View on GitHub"></a></div>
blog:
  cc_license:  http://creativecommons.org/licenses/by-sa/4.0/
  cc_license_image: /assets/images/theme/cc-by-sa.png
  footer_content: For man is man and master of his fate.

disqus:
  shortname: todebug
  public_key: 8ayEhSuQZP6P8nuIUTKmI99NFEOuI6idwr26SUF6lIpwzcxfpZh5zCTb4PSmCWXe
google_analytics: 'UA-100095499-2'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
